services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wawatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-animeservice:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wawatch_animeservicedb
    volumes:
      - postgres_animeservice_data:/var/lib/postgresql/data
      - ./postgres-anime-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wawatchdb_test_user_svc
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wawatch
      - DB_PORT=5432
      - ANIME_SERVICE_URL=http://anime-service:8082  # <--- ADD THIS LINE
      - USER_SERVICE_PORT=8080 # If your backend main.go uses this
      - JWT_SECRET=your_strong_jwt_secret_here # Make sure this is set
      - CORS_ALLOWED_ORIGINS_USER_SVC=http://localhost # Or your frontend's host port
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  anime-service:
    build:
      context: ./anime-service
    environment:
      - DB_HOST=postgres-animeservice  # Updated host to match service name
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wawatch_animeservicedb
      - DB_PORT=5432  # Note: host port is 5433, but container port is still 5432
      - ANIME_SERVICE_PORT=8082 # If your anime-service main.go uses this
      - CORS_ALLOWED_ORIGINS=http://localhost # Or your frontend's host port
    ports:
      - "8081:8082"
    depends_on:
      postgres-animeservice:  # Updated dependency
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - anime-service

volumes:
  postgres_data:
  postgres_animeservice_data: